In [1]:
import sncosmo

In [3]:
!ls ..

LICENSE  README.md  data  doc  examples  src

In [4]:
!ls ../data/

DES_BLIND+HOSTZ.tar.gz	  unblind_hostz_1.csv  unblind_nohostz_1.csv
DES_BLINDnoHOSTZ.tar.gz   unblind_hostz_2.csv  unblind_nohostz_2.csv
DES_UNBLIND_KEY.tar.gz	  unblind_hostz_3.csv  unblind_nohostz_3.csv
SIMGEN_PUBLIC_DES	  unblind_hostz_4.csv  unblind_nohostz_4.csv
SIMGEN_PUBLIC_DES.tar.gz  unblind_hostz_5.csv  unblind_nohostz_5.csv

In [1]:
!ls ../data/SIMGEN_PUBLIC_DES/|head -3

ls: ../data/SIMGEN_PUBLIC_DES/: No such file or directory

In [7]:
data = sncosmo.read_snana_ascii('../data/SIMGEN_PUBLIC_DES/DES_SN000017.DAT', 'OBS')

In [8]:
type(data[0])

collections.OrderedDict

In [9]:
import pandas as pd
import numpy as np

In [10]:
data = pd.DataFrame(np.asarray(data[1]['OBS']))

In [11]:
grouped = data.groupby('FLT')

In [12]:
grouped.get_group('g').query('SNR >= 0')

          MJD FLT FIELD  FLUXCAL  FLUXCALERR   SNR     MAG   MAGERR  SIM_MAG
4   56179.023   g  NULL   6.1220       6.377  0.96  25.533  102.467   60.656
8   56180.031   g  NULL   2.8650       5.671  0.51  26.357  101.643   59.296
12  56188.004   g  NULL   5.2790       5.677  0.93  25.694  102.306   52.990
16  56189.004   g  NULL   5.9300       5.647  1.05  25.567    3.298   51.733
33  56216.215   g  NULL   7.3900       2.487  2.97  25.328    0.445   25.735
37  56221.004   g  NULL  38.9500       5.337  7.30  23.524    0.160   23.707
41  56222.016   g  NULL  39.9200       6.345  6.29  23.497    0.188   23.572
45  56229.012   g  NULL  38.1200       9.885  3.86  23.547    0.326   23.537
49  56231.012   g  NULL  41.2500       7.017  5.88  23.461    0.202   23.592
53  56236.027   g  NULL  30.7400       5.282  5.82  23.781    0.205   23.769
57  56238.023   g  NULL  31.9600       3.739  8.55  23.739    0.135   23.856
61  56244.047   g  NULL  16.3400       4.247  3.85  24.467    0.328   24.098
65  56246.082   g  NULL  15.2300       2.921  5.21  24.543    0.232   24.165
69  56254.199   g  NULL  15.2700       6.162  2.48  24.541    0.561   24.417
73  56261.066   g  NULL  14.0100       6.949  2.02  24.634    0.744   24.673
77  56276.152   g  NULL  12.3800       4.062  3.05  24.768    0.431   25.298
85  56292.109   g  NULL   0.9879       7.769  0.13  27.513  100.487   25.958
89  56305.043   g  NULL   0.7818       2.881  0.27  27.767  100.233   26.481

In [13]:
!ls -al ../MINION_1016_10YR_DDF/

total 1008304
drwxrwxr-x 12 dreiss staff       408 May 28 06:48 .
drwxrwxr-x 21 dreiss staff       714 Jul  1 16:16 ..
-rw-rw-r--  1 dreiss staff  23555520 May 28 06:48 LSST_Ia_HEAD.FITS
-rw-rw-r--  1 dreiss staff 391351680 May 28 06:48 LSST_Ia_PHOT.FITS
-rw-rw-r--  1 dreiss staff  19189440 May 28 05:25 LSST_NONIa_HEAD.FITS
-rw-rw-r--  1 dreiss staff 557686080 May 28 05:25 LSST_NONIa_PHOT.FITS
-rw-rw-r--  1 dreiss staff  40709562 May 28 06:48 MINION_1016_10YR_DDF.DUMP
drwxrwxr-x  8 dreiss staff       272 May 28 06:48 MINION_1016_10YR_DDF.FILTERS
-rw-rw-r--  1 dreiss staff         0 May 28 06:48 MINION_1016_10YR_DDF.IGNORE
-rw-rw-r--  1 dreiss staff        39 May 28 06:48 MINION_1016_10YR_DDF.LIST
-rw-rw-r--  1 dreiss staff       625 May 28 06:48 MINION_1016_10YR_DDF.README
drwxrwxr-x  8 dreiss staff       272 May 28 06:48 misc

In [111]:
from astropy.io import fits
header = fits.open('../MINION_1016_10YR_DDF/LSST_Ia_HEAD.FITS')
snid = header[1].data['SNID']
print(snid)
print(len(snid))

sn_first_10 = sncosmo.read_snana_fits('../MINION_1016_10YR_DDF/LSST_Ia_HEAD.FITS', 
                                      '../MINION_1016_10YR_DDF/LSST_Ia_PHOT.FITS',
                                     snids=snid[:10])
print type(sn_first_10[0])
#sn_first_10[0]

header = pd.DataFrame(np.asarray(header[1].data))

['13' '31' '42' ..., '1364131' '1364136' '1364137']
65732
<class 'astropy.table.table.Table'>

In [112]:
data = pd.DataFrame(np.asarray(sn_first_10[0]))
grouped = data.groupby('FLT')
grouped.get_group('r').query('MAG < 99')

,MJD,FLT,FIELD,TELESCOPE,PHOTFLAG,PHOTPROB,FLUXCAL,FLUXCALERR,MAG,MAGERR,PSF_SIG1,PSF_SIG2,PSF_RATIO,SKY_SIG,SKY_SIG_T,RDNOISE,ZEROPT,ZEROPT_ERR,GAIN,SIM_MAGOBS
0,60902.180,r,NULL,LSST,0,0.0,0.151862,0.909222,29.546381,98.453621,1.66,0.0,0.0,133.320007,-9.0,1.12,34.840000,0.005,1.0,32.748344
8,60920.199,r,NULL,LSST,0,0.0,1.518787,1.858520,27.046259,100.953743,2.94,0.0,0.0,161.100006,-9.0,1.12,34.889999,0.005,1.0,28.630016
12,60933.227,r,NULL,LSST,0,0.0,0.249253,0.800520,29.008398,98.991600,1.88,0.0,0.0,103.629997,-9.0,1.12,34.840000,0.005,1.0,28.010450
16,60947.023,r,NULL,LSST,0,0.0,3.254426,1.414858,26.218813,0.619349,2.41,0.0,0.0,136.339996,-9.0,1.12,34.790001,0.005,1.0,28.594679
32,60964.020,r,NULL,LSST,0,0.0,0.095845,0.832614,30.046074,97.953926,1.82,0.0,0.0,108.320000,-9.0,1.12,34.810001,0.005,1.0,29.767111
36,60975.070,r,NULL,LSST,0,0.0,0.146913,0.800196,29.582350,98.417648,1.76,0.0,0.0,112.720001,-9.0,1.12,34.860001,0.005,1.0,30.474836
40,60978.074,r,NULL,LSST,0,0.0,1.853492,1.504471,26.830021,1.812773,2.34,0.0,0.0,165.330002,-9.0,1.12,34.900002,0.005,1.0,30.844015

We also need things like redshift, RA, Dec, etc. Get them from the 'HEAD' file?

In [137]:
print header.SNID[0], type(header.SNID[0]), header.SNID[0] is '13'
print type(header), header.shape
print header.ix[0].SNTYPE
header.ix[0][60:79]

13           <type 'str'> False
<class 'pandas.core.frame.DataFrame'> (65732, 79)
1

SIM_SALT2beta         3.2
SIM_PEAKMAG_u          -9
SIM_PEAKMAG_g          -9
SIM_PEAKMAG_r     28.2005
SIM_PEAKMAG_i     26.1942
SIM_PEAKMAG_z     25.1402
SIM_PEAKMAG_Y     25.0387
SIM_EXPOSURE_u          1
SIM_EXPOSURE_g          1
SIM_EXPOSURE_r          1
SIM_EXPOSURE_i          1
SIM_EXPOSURE_z          1
SIM_EXPOSURE_Y          1
SIM_GALFRAC_u          -9
SIM_GALFRAC_g          -9
SIM_GALFRAC_r          -9
SIM_GALFRAC_i          -9
SIM_GALFRAC_z          -9
SIM_GALFRAC_Y          -9
Name: 0, dtype: object

In [163]:
ra = header.RA
dec = header.DECL
sntype = header.SNTYPE
mwebv = header.MWEBV
hostid = header.HOSTGAL_OBJID
hostz = header.HOSTGAL_PHOTOZ
hostzerr = header.HOSTGAL_PHOTOZ_ERR
specz = header.HOSTGAL_SPECZ
speczerr = header.HOSTGAL_SPECZ_ERR
sim_z = header.SIM_REDSHIFT_HELIO

filters = [i[-1] for i in header.columns.values if i.startswith('SIM_PEAKMAG_')]
filters

['u', 'g', 'r', 'i', 'z', 'Y']

In [129]:
data = pd.DataFrame(np.asarray(sn_first_10[0]))
data = data.query('MAG < 99')
data = data[['MJD','FLT','FLUXCAL','FLUXCALERR']]
grouped = data.groupby('FLT')
grouped.get_group('r')

          MJD FLT   FLUXCAL  FLUXCALERR
0   60902.180   r  0.151862    0.909222
8   60920.199   r  1.518787    1.858520
12  60933.227   r  0.249253    0.800520
16  60947.023   r  3.254426    1.414858
32  60964.020   r  0.095845    0.832614
36  60975.070   r  0.146913    0.800196
40  60978.074   r  1.853492    1.504471

In [182]:
tmp = pd.DataFrame(data.ix[0]).transpose()
tmp[:] = np.nan
tmp.FLT = 'r'
tmp

   MJD FLT FLUXCAL FLUXCALERR
0  NaN   r     NaN        NaN

In [170]:
print grouped.groups.keys()
print filters
pd.merge(grouped.get_group('r'), grouped.get_group('i'), on=['MJD'], how='outer', suffixes=('_r', '_i'))

['Y', 'i', 'r', 'z']
['u', 'g', 'r', 'i', 'z', 'Y']

          MJD FLT_r  FLUXCAL_r  FLUXCALERR_r FLT_i  FLUXCAL_i  FLUXCALERR_i
0   60902.180     r   0.151862      0.909222   NaN        NaN           NaN
1   60920.199     r   1.518787      1.858520   NaN        NaN           NaN
2   60933.227     r   0.249253      0.800520   NaN        NaN           NaN
3   60947.023     r   3.254426      1.414858   NaN        NaN           NaN
4   60964.020     r   0.095845      0.832614   NaN        NaN           NaN
5   60975.070     r   0.146913      0.800196   NaN        NaN           NaN
6   60978.074     r   1.853492      1.504471   NaN        NaN           NaN
7   60920.215   NaN        NaN           NaN     i   2.153496      2.980007
8   60933.242   NaN        NaN           NaN     i   3.715618      1.509807
9   60947.039   NaN        NaN           NaN     i   3.141938      2.225110
10  60950.074   NaN        NaN           NaN     i   0.445711      2.607434
11  60958.031   NaN        NaN           NaN     i   1.574774      1.840748
12  60961.031   NaN        NaN           NaN     i   4.379611      1.776425
13  60964.035   NaN        NaN           NaN     i   2.796502      1.412402
14  60975.090   NaN        NaN           NaN     i   1.153313      1.355829
15  60992.051   NaN        NaN           NaN     i   2.176445      1.639107

In [186]:
df = pd.DataFrame(data.ix[0]).transpose()
df[:] = np.nan

try:
    df = grouped.get_group(filters[0]) # grouped.groups.keys()[0])
except:
    df.FLT = filters[0]

for f in filters[1:]: #grouped.groups.keys()[1:]:
    print f
    tmp = pd.DataFrame(data.ix[0]).transpose()
    tmp[:] = np.nan
    tmp.FLT = f
    try:
        tmp = grouped.get_group(f)
    except:
        pass
    df = pd.merge(df, tmp, on=['MJD'], how='outer', suffixes=('', '_'+f))
df

g
r
i
z
Y

,MJD,FLT,FLUXCAL,FLUXCALERR,FLT_g,FLUXCAL_g,FLUXCALERR_g,FLT_r,FLUXCAL_r,FLUXCALERR_r,FLT_i,FLUXCAL_i,FLUXCALERR_i,FLT_z,FLUXCAL_z,FLUXCALERR_z,FLT_Y,FLUXCAL_Y,FLUXCALERR_Y
0,NaN,u,NaN,NaN,g,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,60902.2,NaN,NaN,NaN,NaN,NaN,NaN,r,0.151862,0.909222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,60920.2,NaN,NaN,NaN,NaN,NaN,NaN,r,1.518787,1.858520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,60933.2,NaN,NaN,NaN,NaN,NaN,NaN,r,0.249253,0.800520,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,60947,NaN,NaN,NaN,NaN,NaN,NaN,r,3.254426,1.414858,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,60964,NaN,NaN,NaN,NaN,NaN,NaN,r,0.095845,0.832614,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,60975.1,NaN,NaN,NaN,NaN,NaN,NaN,r,0.146913,0.800196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,60978.1,NaN,NaN,NaN,NaN,NaN,NaN,r,1.853492,1.504471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,60920.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,i,2.153496,2.980007,NaN,NaN,NaN,NaN,NaN,NaN
9,60933.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,i,3.715618,1.509807,NaN,NaN,NaN,NaN,NaN,NaN
10,60947,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,i,3.141938,2.225110,NaN,NaN,NaN,NaN,NaN,NaN
11,60950.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,i,0.445711,2.607434,NaN,NaN,NaN,NaN,NaN,NaN
12,60958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,i,1.574774,1.840748,NaN,NaN,NaN,NaN,NaN,NaN
13,60961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,i,4.379611,1.776425,NaN,NaN,NaN,NaN,NaN,NaN
14,60964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,i,2.796502,1.412402,NaN,NaN,NaN,NaN,NaN,NaN
15,60975.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,i,1.153313,1.355829,NaN,NaN,NaN,NaN,NaN,NaN
16,60992.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,i,2.176445,1.639107,NaN,NaN,NaN,NaN,NaN,NaN
17,60905.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,z,0.871530,2.651292,NaN,NaN,NaN
18,60920.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,z,10.103189,4.158594,NaN,NaN,NaN
19,60933.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,z,7.086959,2.145532,NaN,NaN,NaN
20,60947.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,z,6.258898,3.055876,NaN,NaN,NaN
21,60950.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,z,14.390807,3.608836,NaN,NaN,NaN
22,60958,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,z,5.379159,2.512275,NaN,NaN,NaN
23,60961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,z,2.601245,2.454101,NaN,NaN,NaN
24,60964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,z,4.336129,1.964984,NaN,NaN,NaN
25,60975.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,z,5.519457,1.954518,NaN,NaN,NaN
26,60978.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,z,1.656097,3.646598,NaN,NaN,NaN
27,60992.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,z,0.752641,2.324166,NaN,NaN,NaN
28,60905.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,0.107521,11.075076
29,60920.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,3.173010,13.562908
30,60933.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,2.084234,9.246275
31,60947.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,15.840936,10.845887
32,60950.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,1.695242,9.132298
33,60958.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,1.181451,10.556520
34,60964.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,18.860376,8.445213
35,60975.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Y,1.576161,8.481765